config/routes.rb
Workspace::Application.routes.draw do
  
resources :users

get 'signup' => 'users#new'
get 'static_pages/about'
get 'static_pages/home'
get 'static_pages/contact'
get 'sign_in' => 'sessions#new'
post 'sign_in' => 'sessions#create'
delete 'sign_out' => 'sessions#destroy'

  root 'static_pages#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :role, presence: true
    validates :password, presence: true, length: { minimum: 6 }
    validates :password_confirmation, presence: true, length: { minimum: 6 }
    # validates :email, format: { with: /\A\S+@\S+\.\S+\z/, message: 'must be a valid email address'}
    
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        @user = User.where(email: params[:session][:email]).first
        
        if @user
                if @user.authenticate(params[:session][:password])  
                    session[:user_id] = @user.id
                    redirect_to root_path, notice: 'Successfully signed in!'
                else
                    flash[:notice] = "Incorrect username or password"
                    render 'new'
                end
        else
            flash[:notice] = "User cannot be found"
            render 'new'
        end
    end
    
    def destroy
        if session[:user_id]
           session[:user_id] = nil
           redirect_to root_path, notice: "successfully signed out"
        end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  
  def create
    # render plain: params[:user].inspect
    @user = User.new(user_params)
    
    if @user.save
      UserMailer.welcome_email(@user).deliver #to send email
      redirect_to @user, notice: 'Successfully created a user'
    else
      flash[:alert] = "User not created, please try again"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      redirect_to @user, notice: 'Successfully updated user!'
    else
      flash[:notice] = "Couldn't update user!"
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.delete
      redirect_to @user, notice: 'Deleted user'
    else
      redirect_to request.referrer, notice: 'Could not destroy user'
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :role, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        if !session[:user_id].blank?
            current_user = User.find(session[:user_id])
        else
            current_user = nil
        end
        
        return current_user
    end
    
    def current_user_logged_in?
        if current_user
            true
        else
            false
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4 col-md-3 col-lg-4 col-lg-offset-4">
    <div class="page-footer"
      <p>All content &copy; Tony Moey 2014</p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">TTT</a>
    </div>
  

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
       <li role="presentation" <%= current_page?(root_path) ? "class=active" :""%>><%= link_to 'Home', root_path %></li>
        <li role="presentation" <%= current_page?(controller: 'static_pages', action: 'about' ) ? "class=active" :""%>><%= link_to 'About Us', static_pages_about_path %></li>
        <li role="presentation" <%= current_page?(controller: 'static_pages', action: 'contact') ? "class=active" :""%>><%= link_to 'Contact Us', static_pages_contact_path %></li>
        
        
        
        
        <% if current_user_logged_in? %>
            <li role="presentation" <%= current_page?(controller: 'users', action: 'index' ) ? "class=active" :""%>><%= link_to 'Users List', users_path %></li>
            <li role="presentation" <%= current_page?(controller: 'users', action: 'edit' ) ? "class=active" :""%>><%= the_link = link_to 'Edit Profile', edit_user_path(current_user) %></li>
            <li role="presentation" <%= current_page?(controller: 'sessions', action: 'destroy' ) ? "class=active" :""%>><%= the_link = link_to 'Sign Out', sign_out_path, method: :delete %></li>
        <%  else %>
            <li role="presentation" <%= current_page?(controller: 'users', action: 'new' ) ? "class=active" :""%>><%= link_to 'Register', new_user_path %></li>
            <li role="presentation" <%= current_page?(controller: 'sessions', action: 'new' ) ? "class=active" :""%>><%= the_link = link_to 'Sign In', sign_in_path %></li>
            
         <% end %>
         
         <!---->
        
      </ul>
    
     
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: "alert alert-#{name}" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= render 'layouts/messages' %>


<div class="container">
<%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
    <h1>Welcome to TonyTellsTime!</h1>
    <p>Sign up and add different timezones to your liking!</p>
    
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control'%>
  </div>
  
  <div class="form-group">
    <%= f.label :role %>
    <%= f.select :role, [['Admin', 'admin'],['User', 'user']]%>  
  </div>
  
  <div class="form-group">
    <%= f.label :password %>
    <%= f.text_field :password, class: 'form-control' %>
  </div>
  
  <div class="form-group">
   <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation, class: 'form-control' %>
  </div>
  
  <% if @user.new_record? %>
    <% submit_label = "Sign Up" %>
  <% else %>
    <% submit_label = "Update" %>
  <% end %>
  
  <%= f.submit submit_label, class: 'btn btn-success'%>
  <!--<button type="submit" class="btn btn-default">Submit</button>-->

<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4 col-md-3 col-lg-4 col-lg-offset-4">
      <div class="page-header">
          <h1>Edit User</h1>
      </div>
        <%= render 'form' %>
        <%= link_to 'Back', users_path %>
    </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4 col-md-3 col-lg-4 col-lg-offset-4">
    
    <div class="page-header">
       <h1>User Listing</h1>
    </div>
<table>
  <tr>
    <th>Name</th>
    <th>Action</th>
  </tr>
  
  <% @users.each do |user| %>

  <tr>
      <td><%= user.name %></td>
      <td><%= link_to "Edit", edit_user_path(user) %> <%= link_to "Delete", user_path(user), method: :delete, confirm: 'Are you sure?' %></td>
  </tr>
  
  <% end %>
</table>
    
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4 col-md-3 col-lg-4 col-lg-offset-4">
      <div class="page-header">
          <h1>Add User</h1>
      </div>
        <%= render 'form' %>
        <%= link_to 'Back', users_path %>
    </div>
</div>

app/views/users/show.html.erb
<h1>User: <%= @user.name %></h1>
<h1>Email: <%= @user.email %></h1>